org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=Entity Crosshair
mod_id=entitycrosshair
mod_version=1.0.0
mod_description=Fully customizable, centered, colored, dynamic crosshair that changes when looking at an entity
mod_archives_name=EntityCrosshair
base_group=tomeko.entitycrosshair

java_version=[VERSIONED]
minecraft_version=[VERSIONED]

stonecutter_version=0.9.5