org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=Entity Crosshair
mod_id=entitycrosshair
mod_version=2.0.0
mod_description=Fully customizable, centered, colored, dynamic crosshair that changes when looking at an entity
mod_archives_name=EntityCrosshair
base_group=tomeko.entitycrosshair

java_version=[VERSIONED]
minecraft_version=[VERSIONED]
fabric_loader_version=0.19.3
fabric_api_version=[VERSIONED]
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10

oneconfig_version=1.0.1
mod_menu_version=[VERSIONED]

stonecutter_version=0.9.6